services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@jobscout.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    networks:
      - app
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgadmin_data:


networks:
  app: {}
