services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d jobscout_db_test && pg_isready -U postgres -d jobscout_db_dev && pg_isready -U postgres -d jobscout_db_prod" ]
      interval: 5s
      timeout: 2s
      retries: 20
    command: postgres -c listen_addresses='*'
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:


networks:
  app: {}
